# Generated by Django 4.0.6 on 2022-07-07 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_quiz_total_marks_quiz_quiz_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 20, 11, 53, 67721)),
        ),
    ]
