# Generated by Django 4.0.6 on 2022-07-07 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_submit_submission_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizType',
            new_name='Type',
        ),
        migrations.AlterField(
            model_name='submit',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 20, 16, 25, 540539)),
        ),
    ]
