# Generated by Django 4.0.6 on 2022-07-07 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_quiz_type_alter_submit_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submit',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 20, 25, 16, 785753)),
        ),
    ]
